version: '3'

tasks:
  build:
    desc: "Build EMS"
    cmds:
      - go build -o bin/ems-server
      - go build -o bin/ems-cli cmd/ems-cli/ems.go
    silent: true

  test:
    desc: "run all the unit tests"
    cmds:
      - go test -v ./...
    silent: true


  clean:
    desc: "clean and clear"
    cmds:
      - rm -f bin/ems-server bin/ems-cli ems.db
    silent: true

